### ISSUE TITLE
test that ipython is working in qiime

### ISSUE THREAD

**Issue by antgonza** [qiime/qiime-deploy#32]
We need to test that ipython is actually working in the latest release. For 1.7.0 we realized that the newest version of ipython is requires newer version of their dependencies. The easiest way to test will be to:
```bash
export SOFTWARE_HOME=/home/ubuntu/qiime_software
$SOFTWARE_HOME/ipython*/bin/ipcluster
```

**Comment by jairideout** [comment]
@gregcaporaso and I tested this on the 1.9.0rc1 AMI and it appears to be working.
