### ISSUE TITLE
Ubuntu 12.04 qiime-deploy dependency package name mismatch

### ISSUE THREAD

**Issue by nathanhaigh** [qiime/qiime-deploy#44]
In the README.md it states the `libmysqlclient16` is one of the qiime-deploy dependencies. This only exists for Ubuntu 10.04. The correct package for Ubuntu 12.04 is `libmysqlclient18`.

**Comment by jairideout** [comment]
Looks like this was fixed sometime in the past. Thanks for reporting the issue!
