### ISSUE TITLE
A few errors

### ISSUE THREAD

**Issue by pvp2101** [qiime/qiime-deploy#82]
Hello!

I followed your examples to the T and thank you so much for the ease of this package.  I wanted to know if you came across any of these errors and how I could go about fixing them.  

I see that Mothur is in my path, so I don't know why it isn't picking it up.  Should I dl these files and install them myself?  

FAIL: test_denoiser_supported_version (**main**.QIIMEDependencyFull)
## denoiser aligner is ready to use

Traceback (most recent call last):
  File "/usr/local/bin/print_qiime_config.py", line 570, in test_denoiser_supported_version
    "Denoiser flowgram aligner not found or not "
AssertionError: Denoiser flowgram aligner not found or not executable. This may or may not be a problem depending on which components of QIIME you plan to use.
# 

FAIL: test_h5py (**main**.QIIMEDependencyFull)
## h5py is installed

Traceback (most recent call last):
  File "/usr/local/bin/print_qiime_config.py", line 709, in test_h5py
    "h5py is not installed. You should install this for "
AssertionError: h5py is not installed. You should install this for improved performance with large BIOM files or if working with BIOM format version 2.x files. For more information, see http://qiime.org/documentation/file_formats.html#biom-file-format-versions

---

Ran 27 tests in 0.247s

FAILED (failures=3, errors=1)
# System information

```
     Platform:  linux2
```

   Python version:  2.7.6 (default, Nov  2 2015, 15:47:43)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
Python executable:  /usr/local/bin/python2.7
# QIIME default reference information

For details on what files are used as QIIME's default references, see here:
 https://github.com/biocore/qiime-default-reference/releases/tag/0.1.3
# Dependency versions

```
            QIIME library version:  1.9.1
             QIIME script version:  1.9.1
  qiime-default-reference version:  0.1.3
                    NumPy version:  1.10.1
                    SciPy version:  0.16.1
                   pandas version:  0.17.0
               matplotlib version:  1.5.0
              biom-format version:  2.1.5
                     h5py version:  Not installed.
                     qcli version:  0.1.1
                     pyqi version:  0.3.2
               scikit-bio version:  0.2.3
                   PyNAST version:  1.2.2
                  Emperor version:  0.9.51
                  burrito version:  0.9.1
         burrito-fillings version:  0.1.1
                sortmerna version:  SortMeRNA version 2.0, 29/11/2014
                sumaclust version:  SUMACLUST Version 1.0.00
                    swarm version:  Swarm 1.2.19 [Nov  2 2015 16:15:50]
                            gdata:  Installed.
```

RDP Classifier version (if installed):  rdp_classifier-2.2.jar
          Java version (if installed):  1.6.0_36
# QIIME config values

For definitions of these settings and to learn how to configure QIIME, see here:
 http://qiime.org/install/qiime_config.html
 http://qiime.org/tutorials/parallel_qiime.html

```
                 blastmat_dir:  /export/apps/qiime/1.8.0/bin/blast-2.2.22-release/data
  pick_otus_reference_seqs_fp:  /usr/local/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
                     sc_queue:  all.q
  topiaryexplorer_project_dir:  None
 pynast_template_alignment_fp:  /usr/local/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set_aligned/85_otus.pynast.fasta
              cluster_jobs_fp:  start_parallel_jobs.py
```

pynast_template_alignment_blastdb:  None
assign_taxonomy_reference_seqs_fp:  /usr/local/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
                     torque_queue:  friendlyq
                    jobs_to_start:  1
                       slurm_time:  None
            denoiser_min_per_core:  50
assign_taxonomy_id_to_taxonomy_fp:  /usr/local/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt
                         temp_dir:  /tmp/
                     slurm_memory:  None
                      slurm_queue:  None
                      blastall_fp:  /export/apps/qiime/1.8.0/bin/blast-2.2.22-release/bin/blastall
                 seconds_to_sleep:  1
# QIIME full install test results
# ...F........F...FE.........

ERROR: test_mothur_supported_version (**main**.QIIMEDependencyFull)
## mothur is in path and version is supported

Traceback (most recent call last):
  File "/usr/local/bin/print_qiime_config.py", line 549, in test_mothur_supported_version
    version_string = stdout.strip().split(' ')[1].strip('v.')
IndexError: list index out of range
# 

FAIL: test_ampliconnoise_install (**main**.QIIMEDependencyFull)
## AmpliconNoise install looks sane.

Traceback (most recent call last):
  File "/usr/local/bin/print_qiime_config.py", line 382, in test_ampliconnoise_install
    "$PYRO_LOOKUP_FILE variable is not set. See %s for help." % url)
AssertionError: $PYRO_LOOKUP_FILE variable is not set. See http://qiime.org/install/install.html#ampliconnoise-install-notes for help.
#

**Comment by jairideout** [comment]
@pvp2101 can you please post these issues on the [QIIME forum](http://forum.qiime.org)? Thanks!
