### ISSUE TITLE
Ubuntu 16.04 Fresh Install

### ISSUE THREAD

**Issue by GloballyWarmDude** [qiime/qiime-deploy#83]
I am trying to install the latest and greatest of QIIME plus Microbiome_helper. (I'm just a sysadmin, I don't really understand what these packages do except in the most basic terms)

I have a fresh install of Ubuntu 16.04 and I've tried following the installation using the Ubuntu 14.04 procedures. Understandably it does not work. I get an error at step 2 which is to install a bunch of packages after the sources.list file is edited.

I suppose I have to decide if I should give up and just install Ubuntu 14.04 on the host or should I try to pick through all of this for a Ubuntu 16.04 OS.

Will Ubuntu 16.04 be supported any time soon?

peter dot mackay at bcchr dot ca

**Comment by antgonza** [comment]
QIIME 2 has succeeded QIIME 1 as of January 1, 2018. More info: https://qiime2.org/. Instructions to install QIIME 2: https://docs.qiime2.org/2018.2/install/.
